### ISSUE TITLE
Support for clustering multipart quests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-api#16] opened 2017-08-17 00:56 UTC
Better condensing/presentation of multi part quests. Probably requires additional metadata, and maybe a different api return format.

**Comment by toddmedema** [comment] 2017-08-20 02:40
See this issue for further brainstorming: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/283

**Comment by toddmedema** [comment] 2018-01-12 20:45
Duplicate of https://github.com/ExpeditionRPG/expedition-api/issues/35

**Closed by toddmedema** 2018-01-12 20:45 UTC
